project:
  type: default
  title: "ia_mas_alla_del_prompt"
  output-dir: .

editor: visual

format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: true
    transition: slide
    self-contained: false

