project:
  type: default
  output-dir: docs
  render:
    - index.qmd

format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: true
    transition: slide
    self-contained: true


