project:
  type: default
  output-dir: docs
  render:
    - index.qmd

format:
  revealjs:
    theme: simple
    slide-number: true
    incremental: true
    transition: slide
    self-contained: true
    logo: "imagenes/Imagen1.jpg"
    footer: "© Sebastián Egaña Santibáñez"

editor: visual

